name: CI

on: 
  workflow_dispatch:
    inputs:
      version:
        description: version
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: scripts
        run: |
          git clone https://github.com/Clinale/miniOneLifeCompile.git
          cd miniOneLifeCompile
          ./getDependencies.sh
          ./cloneRepos.sh
          ./applyFixesAndOverride.sh

          ./makeWindows.sh ${{ inputs.version }}
          ./cleanOldBuildsAndOptionallyCaches.sh

          ./makeLinux.sh ${{ inputs.version }}
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ inputs.version }}
          release_name: v${{ inputs.version }}
          body: |
            Update to v${{ inputs.version }}.

            This is for Two Hours One Life v${{ inputs.version }}.
            
            升級到 v${{ inputs.version }}。
            
            這對應到 Two Hours One Life v${{ inputs.version }}。
            如何安裝：
            https://github.com/Clinale/miniOneLifeCompile.git
      - name: upload windows #Windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ../output/windows/OneLife_Windows_v${{ inputs.version }}.zip
          asset_name: OneLife_Windows_v${{ inputs.version }}.zip
          asset_content_type: application/zip
      - name: upload linux #Linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ../output/linux/OneLife_Linux_v${{ inputs.version }}.zip
          asset_name: OneLife_Linux_v${{ inputs.version }}.zip
          asset_content_type: application/zip
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
  