name: Get latest release version

on:
  schedule:
    - cron:  '30 * * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: check version mismatch
        id: mismatch
        run: |
          jason=$(curl --silent -f https://raw.githubusercontent.com/Clinale/OneLife/master/gameSource/game.cpp)
          if [ $? -ne 0 ]; then echo "Failed to fetch game source version"; exit 1; fi

          jason=$(echo "$jason" | grep -o -P '(?<=int versionNumber = )\d+')
          if [ -z "$jason" ]; then echo "Failed to extract game source version"; exit 1; fi

          dataversion=$(curl --silent -f https://raw.githubusercontent.com/Clinale/OneLifeData7/master/dataVersionNumber.txt)
          if [ $? -ne 0 ]; then echo "Failed to fetch data version"; exit 1; fi

          if [ $jason -lt $dataversion ]; then jason="$dataversion"; fi

          mine=$(curl --silent -f https://api.github.com/repos/Clinale/OneLife/releases/latest | jq -r .tag_name)
          if [ $? -ne 0 ]; then echo "Failed to fetch latest release version"; fi

          if [ -n "$mine" ]; then
                  mine=$(echo "$mine" | grep -o -P '(?<=v)\d*')
                  if [ -z "$mine" ]; then echo "Failed to extract latest release version"; exit 1; fi
          fi

          if [ "$jason" = "$mine" ]; then
              is_mismatch="false"
          else
              is_mismatch="true"
          fi
          echo "is_mismatch: $is_mismatch, version: $jason"
          echo "::set-output name=is_mismatch::$is_mismatch"
          echo "::set-output name=version::$jason"
      - name: call make_release
        if: steps.mismatch.outputs.is_mismatch == 'true'
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/Clinale/OneLife/actions/workflows/make_release.yml/dispatches \
            -d '{"ref":"master", "inputs": { "version":"${{ steps.mismatch.outputs.version }}" }}' 
